### ISSUE TITLE
Abort train error

### ISSUE THREAD

**Issue by xxz2233** [JanEGerken/HEAL-SWIN#4]
When i use ```python run.py --env local train```to train. I have some error.
```
(heal_swin) tmzhou@boot-SYS-7049GP-TRT:~/HEAL-SWIN$ python run.py --env local train
--------- Compute environment --------
Using environment specified in /data1/home/tmzhou/HEAL-SWIN/compute_environment/current_environment.py
Project paths:
  datasets: /data1/home/tmzhou/HEAL-SWIN/datasets /data1/home/tmzhou/HEAL-SWIN/datasets
  mlruns: /data1/home/tmzhou/HEAL-SWIN/mlruns /data1/home/tmzhou/HEAL-SWIN/mlruns
  containers: /data1/home/tmzhou/HEAL-SWIN/containers /data1/home/tmzhou/HEAL-SWIN/containers
  slurm: /data1/home/tmzhou/HEAL-SWIN/slurm /data1/home/tmzhou/HEAL-SWIN/slurm
  matplotlib_cache: /data1/home/tmzhou/HEAL-SWIN/mpl_cache /data1/home/tmzhou/HEAL-SWIN/mpl_cache
Container specifications:
  singularity_container_name: heal_swin_container.sif
Logging specifications:
  mlflow_backend: filesystem
**** These values can be specified by creating (or copying) a new file current_environnment.py ****



running: python3 -u /data1/home/tmzhou/HEAL-SWIN/heal_swin/train.py
Traceback (most recent call last):
  File "/data1/home/tmzhou/HEAL-SWIN/heal_swin/train.py", line 298, in <module>
    main()
  File "/data1/home/tmzhou/HEAL-SWIN/heal_swin/train.py", line 283, in main
    train_config = utils.get_config_from_config_path(args.config_path, "get_train_run_config")
  File "/data1/home/tmzhou/HEAL-SWIN/heal_swin/utils/utils.py", line 211, in get_config_from_config_path
    assert os.path.isfile(abs_path), f"configuration at {abs_path} not found"
AssertionError: configuration at /data1/home/tmzhou/HEAL-SWIN/run_configs/default_train_run_config.py not found
```
I think maybe there are some floder missing? Could you please tell me how to resolve this? Thank you so much for your time.

**Comment by JanEGerken** [comment]
Thanks for your interest in our work!

I’ve pushed an update to `setup.py`. Could you run `pip install -e .` again and check if it works?
